### ISSUE TITLE
Increase message size limit

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#103]
Some managers are having trouble sending images through the mailing list. Current limit is 5242880 bytes which I assume is the default

**Comment by jmrtns** [comment]
Increased to 25MB as this is the most common sending limit among Email providers

**Comment by mitar** [comment]
Sorry, but I think managers should just make images smaller. There is no point of just attaching huge photos to e-mails. Who need 25 MB e-mails going to 140+ people?

**Comment by jmrtns** [comment]
Gifs, multiple photos, high quality photos. What's the problem with it,
some managers send multiple emails per week, others prefer to send single
large emails

**Comment by mitar** [comment]
That they could make photos smaller before sending. I mean, maybe I am old, but 25 MB e-mails look really too big. If you have 10 GB e-mail space, that is then only 400 such e-mails.

**Comment by jmrtns** [comment]
It's also 5.2MB/ HD image. Gmail is 15GB, bmail is unlimited, yahoo mail is
1TB (wow they're desprate). 600 emails is alot, especially with how scarce
large emails like that are.

**Comment by mitar** [comment]
But why would you send such large image to a mailing list? If it is important, then we should preserve it, so we should put it on the file server. If it is not important, then sender can make it smaller, resize it.

**Comment by mitar** [comment]
Anyway, I do not really care.

But I do wonder how you changed the limit.

**Comment by jmrtns** [comment]
In the admin page of the respective list, under send/recieve, there is a
message size list field

**Comment by mitar** [comment]
Cool.
