### ISSUE TITLE
address server1 disk usage

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#106]
There has been an email from server 1s chron deamon every hour for the past two days now. the initial message is 92% disk usage on the boot partition, not sure what's going on with that but the drive has plenty of free space in case the boot partition needs to be expanded for some reason.

**Comment by mitar** [comment]
Have you even looked what is using the space? Ccc.

**Comment by jmrtns** [comment]
looking at it now

**Comment by jmrtns** [comment]
why are there so many kernel versions...

**Comment by mitar** [comment]
Autoupgrade.

Just remove old ones. :-)

BTW, the same issue is on server2 as well.

**Comment by jmrtns** [comment]
I'm also trying something with this git issue by outlining my thought process, I wasn't really asking for help but I appreciate it =)

**Comment by jmrtns** [comment]
just ran 
`rm *xx-generic a bunch of times `

where xx is the version number. made a mistake because initrd.img's last version was one less than the last version of everything else and accidentally deleted all server1's initrd images but I just coppied over the image from server2.

There's probably a better way to do this other than manually

**Comment by mitar** [comment]
> I was also trying something with this git issue by outlining my thought process, I wasn't really asking for help but I appreciate it =)

That is great. I jumped on only because you jumped to an invalid conclusion that it is a log rotate issue. If you would just write "disk is getting full" and then started investigating, I would not interfere. :-)

> just ran rm *xx-generic a bunch of times

NOOOO. You should never ever remove system files on Debian manually. Use `dpkg -S` to find a package which installed them and then remove a package.

**Comment by mitar** [comment]
> but I just coppied over the image from server2.

The same as above. Find a package of the file you removed by accident, and then do `apt-get install --reinstall` to get it back. Copying from other servers is dangerous.

**Comment by jmrtns** [comment]
I know you shouldn't do it, but it's a fun test ground since server1 isn't really used. I like taking things apart =)

I know copying the initrd won't work, but I was curious what exactly it would do before properly fixing it =p It should not be done because server2 uses software RAID thus copying it over will unnecessarily load the mdm modual in init. besides that and more importantly, the initrd of server2 has the root partition on /dev/mapper/server2-vg-root instead of *server1*

**Comment by mitar** [comment]
I think VirtualBox is a great place to play with such things. :-)

**Comment by jmrtns** [comment]
But where's the fire?

**Comment by jmrtns** [comment]
Also, this stack exchange has more detailed answers on how to properly clean a debian boot partition

http://askubuntu.com/questions/89710/how-do-i-free-up-more-space-in-boot

The reason to not manually delete old files is because they are sometimes still referenced by other things. This thread is mostly things I have done in the past, my thought process during those times, what things worked/didn't because I can forsee other network managers doing the same thing as I did in my earlier years, and then crying horrid tears of frustration as everything stops working

**Comment by jmrtns** [comment]
Now server1 is officially broken since the kernel version in use was actually older than the latest kernel image since the server was awaiting restart and I deleted the in use kernel manually. Now I'll document how to fix it =)

**Comment by jmrtns** [comment]
http://askubuntu.com/questions/28099/how-to-restore-a-system-after-accidentally-removing-all-kernels

**Comment by jmrtns** [comment]
This thread is making me sound insane...

**Comment by jmrtns** [comment]
Also, accidentally ran the command on both server1 and server2.... sometimes you play with fire and get burned... learning from mistakes is fun

**Comment by mitar** [comment]
BTW, you can always do `mv` instead of `rm`, test things, and then remove for real once you figure out that it works.
