### ISSUE TITLE
Member not getting all emails

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#108]
A member is getting some emails and not others on there personal email for some reason. They have also showed me instances of where they get replies to a thread but not the original message in the thread, I'm not sure if this is an issue with our server or with our server's interaction with Gmail.

**Comment by mitar** [comment]
Do they use personal server or Gmail?

**Comment by jmrtns** [comment]
Gmail but I'm not sure if they're using mail forwarding from one Gmail to another

**Comment by jmrtns** [comment]
"omg my bmail was marking km emails as spam so it never forwarded to gmail "
