### ISSUE TITLE
Kingman "the internet is slow" guide

### ISSUE THREAD

**Issue by clonm** [cloyne/network#118]
We should help @kngnm debug and also write up a flow chart or something of debugging steps

**Comment by kngnm** [comment]
Update:
- I connected the PoE of `kng-router` into the network closet switch.  I simultaneously ran `speedtest-cli` on `toadserver` (connected via the network closet switch) and my laptop connected to `kng-router` by ethernet.  The differences between the speeds were insignificant.
- I saved a backup of the configuration for `kng-router` and factory reset it.  I connected the PoE of `kng-router` to the kng-clo antenna and connected the network closet switch to `kng-router`.  I then ran speedtest-cli from toadserver.  The speed was 7 Mb/s.
- I looked carefully at the diff between the configurations for `clo-router` and `kng-router`.  I didn't find any unexpected differences between the two.  Of course, I'm no expert.  This might be worth looking into further.
- I skimmed through this [this](http://catalogue.pearsoned.co.uk/samplechapter/0789732556.pdf) article on networking devices.  On page 124 it explains the difference between full and half duplex ethernet communication.  Essentially, full duplex mode allows an ethernet port to send and receive data at the same time, increasing speed.  Half-duplex does not. 
- I later found [this](https://arstechnica.com/civis/viewtopic.php?f=10&t=583367) forum post.  The OP was also trying to set up a subnet and encountered a bandwidth bottleneck.    They found a solution by changing autonegotiation settings setting on their router.
- That lead me to the [autonegotiation wikipedia page](https://en.wikipedia.org/wiki/Autonegotiation).   In a nutshell, the ethernet ports on many network devices can be configured to use full or half duplex.  If two connected ethernet ports are in different modes, it causes performance issue (the Duplex Mismatch explains why, but I don't fully understand).  Autonegotiation allows two ethernet ports to decide on a duplex mode based on the capabilities of both ports.
- The clo-kng antenna was connected to port ether1 on `kng-router`.  Ether1 was set to autonegotiate.  However, the ethernet port on the antenna was set to Full Duplex 100Mb/s.  As detailed in the Wikipedia article, this causes a Duplex Mismatch.  This may be why the internet was slow with the router. 

Potential Solution: set ether1 to Full Duplex 100Mb/s.  I will have to wait for a good time to drop the internet to try this.  I will keep you updated.    

@clonm

**Comment by kngnm** [comment]
Update:
I have corrected the Duplex Mismatch using the solution above.  It seems to have resolved the speed issues.  I have been consistently seeing speeds between 20 and 40Mb/s using `speedtest-cli` on my laptop.   I am working on trying to set up the router as it was historically.  It is now setup to use the 10.20.96.0/22 ip range as specified on the mesh github page.  I have also been working to configure it to use Cloyne's DNS server on server2.cloyne.  The idea is that if the router's configuration matches as closely as possible to the last router that was used on the network, problems like this one will probably not come up in the future.  Thanks for your support.
@clonm

**Comment by clonm** [comment]
https://github.com/cloyne/network/issues/120
