### ISSUE TITLE
IPv4 for Kingman

### ISSUE THREAD

**Issue by clonm** [cloyne/network#121]
> I have a raspberry pi with a nginx reverse proxy server installed on it. If it could be set up to have ip address 64.62.133.46 on the cloyne network (presumably by attaching it to the router and configuring it like one of Cloyne's servers) I could host the rocket chat server by ssh tunneling into the pi from the host machine. I think this solution may be less time intensive than routing the packets. I would only need help setting up the pi on the cloyne network; the rest I have already prepared at home. Let me know if you see any flaws with this solution and/or would be willing to help me implement it.

_Originally posted by @kngnm in https://github.com/cloyne/network/issues/117#issuecomment-455957087_

> Great! I've been working at it from the other end - I got DNS to work and am now trying to figure out all the layers of nginx proxies on server3 to get letsencrypt to register.
> 
> I think I know enough to map .46 to Kingman now - although maybe Cloyne should vote on that since it's technically a finite house resource? I feel like not though - council's long enough already and it's been sitting unused for 4 years... Do you have a domain name registered? or are you thinking kingman.cloyne.org?
> 

_Originally posted by @clonm in https://github.com/cloyne/network/issues/117#issuecomment-456279073_

Moving this to its own thread

**Comment by clonm** [comment]
A kingman network manager from 20 years ago named Ping registered kingmanhall.org.  I got in touch with him and he helped me change it to resolve to 64.62.133.46.  I hope that works.  Sorry if I jumped the gun.

_Originally posted by @kngnm in https://github.com/cloyne/network/issues/117#issuecomment-456280890_

**Comment by clonm** [comment]
@kngnm I don't think anything server-specific is hard-coded in the router config. It looks like the configurations for connecting the Cloyne servers to our router are all handled by Salt, specifically the [network.sls files](https://github.com/cloyne/servers/blob/master/pillars/server2/network.sls). maybe you can look into setting up salt, or at least reverse engineering the relevant parts? and as always, please document :)

**Comment by clonm** [comment]
Also would you rather use our nameservers?

**Comment by kngnm** [comment]
@clonm I think kingmanhall.org might be easier for people to remember.  Unless there are benefits to using a subdomain on cloyne.org, I'd rather stick to kingmanhall.org.  I have started looking into saltstack and am currently trying to set up the raspberry pi to be compatible with the system.  If I come up with something that works, I'll send you a pull request.
