### ISSUE TITLE
Replacing Cisco APs with UniFi APs

### ISSUE THREAD

**Issue by mitar** [cloyne/network#26]
This ticket serves to document the process of replacing Cisco APs with UniFi APs.

We replaced all of them with UniFi AP PRO on February 1 2015. We kept the same channels as they were before.

But there are issues. Pings are not instead 10 ms more around 300 ms very often. Also things simply stop working for clients, despite them being connected to the AP.

I configured now that all APs have "medium" (21 dbm) transmission power.

I also configured [RSSI](http://community.ubnt.com/t5/UniFi-Configuration-Examples/UniFi-Set-minimum-RSSI-for-clients/ta-p/522637), so that clients with bad signal will be kicked off. `config.properties` is now:

```
config.minrssi.0418d6206044.ng=25
config.minrssi.0418d62058df.ng=25
config.minrssi.0418d6205d20.ng=25
config.minrssi.0418d6205cfe.ng=25
config.minrssi.0418d62059c8.ng=25
config.minrssi.0418d6205a1f.ng=25
config.minrssi.0418d62059c7.ng=25
config.minrssi.0418d62058e4.ng=25
config.minrssi.0418d6205fe6.ng=25
```

**Comment by mitar** [comment]
Yesterday night I reconfigured all APs to have auto both for the channel and transmission speed and things started working better I think. But I am not sure if that was because I was also running controller. Does controller have to be online all the time? Then we should install it on the server. Anyone wanna find/prepare a Docker image for it?

**Comment by mitar** [comment]
Done. We reflashed all UniFi with custom OpenWrt because original firmware had issues. Latency was high, and occasionally they just froze for few minutes.

**Comment by ahdinosaur** [comment]
does this mean we're using OpenWrt for all the things?!

**Comment by mitar** [comment]
Yes. :-)

**Comment by ahdinosaur** [comment]
:cake:

**Comment by mitar** [comment]
Our own custom firmware. :-)

https://github.com/cloyne/network/tree/master/unifi

**Comment by mitar** [comment]
We also have a wireless link between Cloyne and Kingman: http://cloyne.org/2015/02/wireless-connection-between-cloyne-and-kingman/
