### ISSUE TITLE
What are 192.168.0.11 and 192.168.0.16 in the network?

### ISSUE THREAD

**Issue by mitar** [cloyne/network#29]
Two Supermicro devices? Maybe some management interface for servers we have?

(They are visible even now when we moved the network to a new IP pool.)

**Comment by ahdinosaur** [comment]
yeah, the two supermicro servers would make sense as i used to have them up at 192.168.0.10 and 192.168.0.15 and i seem to recall them having two ethernet ports. also they have their own special management interface, but i never played around with it, so maybe that. although really i have no idea what y'all are up to, just sharing what i can offer. :smile_cat:

**Comment by mitar** [comment]
Thanks! :-)

So they have two interfaces, but only one is plugged in. Also, they have been reinstalled.

So this seems to be some management interface which kicks in. But it is interesting that it is then reusing the same ethernet port. Often management interfaces are on a separate ports.

**Comment by mitar** [comment]
Not really an issue. Let's keep this around for documentation but I do not think we should do anything about this.
