### ISSUE TITLE
Inventory of public computers

### ISSUE THREAD

**Issue by mitar** [cloyne/network#3]

**Comment by jmrtns** [comment]
this is already done here https://github.com/cloyne/public-computers perhaps we should consolidate audio-video, public computers, and network into one location as you suggested?

**Comment by mitar** [comment]
Yes, I would prefer one repository. You create a new file in the root of this repository and put stuff there.

**Comment by jmrtns** [comment]
do i make "audio-video.md" and "public-computer.md" which are copies of their respective README.md files or should they be one file?

**Comment by mitar** [comment]
You can make it separate.
