### ISSUE TITLE
Verify configuration of switches

### ISSUE THREAD

**Issue by mitar** [cloyne/network#31]
Switches should be configured that DHCP traffic from non-router cannot go through. We should check all switches and see if this was configured. We should check if we can configure this per each port (so no non-router DHCP traffic can spread even around the same switch). Also, now that we moved IP range of the router, do we have to change anything on switches? Or is the rule based on the MAC address?

**Comment by sreezon101** [comment]
It looks like it can only be done via ports (there's no other way to differentiate what a router is other than telling the switches what port it's on). We would have to enable it on that one port and disable it on everything else.

**Comment by ahdinosaur** [comment]
once upon a time this was configured, but the switches seem to reset their config when they feel like it. we did it by having the wire connected in the direction of the router always the highest (i think) physical port with that port allowing DHCP traffic and all other ports blocking DHCP traffic, so the physical ports might still be the same but the switch config may have been reset.

**Comment by mitar** [comment]
Hm. We should then document this and verify if physical ports are still connected in this way.

@sreezon101, can you do that? So:
* [ ] find for each switch their uplink cable and mark the cable
* [ ] move all uplink cables to the easy to define port on the switch (if I understand, most are probably like that)
* [ ] configure that only that one port can have DHCP traffic
* [ ] document that fact and how that was configured in the readme under the switches section

**Comment by sreezon101** [comment]
I'll do it friday night.

**Comment by sreezon101** [comment]
I was able to do all of them except C3 because that switch is locked inside a box that I don't have a key to. Also, all DHCP traffic has been transferred to port 1 (and is only allowed on port 1), which is now the default gateway port of all the switches I configured.

**Comment by mitar** [comment]
Great!

@jmrtns, why is that one locked? Where is the key?

**Comment by mitar** [comment]
@sreezon101, can you do this? Did you get access to the locked cabinet?

**Comment by jmrtns** [comment]
The cabinet is now unlocked so you can now configure it.

**Comment by sreezon101** [comment]
All good.
