### ISSUE TITLE
Ethernet in maintenance room

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#32]
I've yet to test WiFi in there since the new firware flashes on the unifis but that might also still be an issue; I'll update. Either way, Ethernet in there would be very nice.

**Comment by mitar** [comment]
I tested WiFi in the maintenance room and I am getting 20 Mbit/s+ download/upload without any problems.

**Comment by jmrtns** [comment]
WiFi has spotty zones and it works some days but not others.

**Comment by mitar** [comment]
Yea, let's do it then!

**Comment by mitar** [comment]
Done.
