### ISSUE TITLE
No ethernet in Kitchen

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#39]
The Ethernet cable connected to the computer in the kitchen does not work.

**Comment by sreezon101** [comment]
Works.

**Comment by mitar** [comment]
What was the problem?

**Comment by mitar** [comment]
What was the problem?

**Comment by sreezon101** [comment]
I suspect that the Ethernet card may have needed a power cycle or that there was an issue with assignment following the configuration of traffic flow control on C3 (probably not). In any case, restarting the machine will probably solve the issue.
