### ISSUE TITLE
Static IP for desktop in maintenance room after running an ethernet cable to the maintenance room.

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#42]
I like to ssh, especially since I have such a weak little computer, and that's hard to do with a dynamic IP

**Comment by mitar** [comment]
Tell me the MAC.

**Comment by mitar** [comment]
Done. `maintenance.cloyne.net` also set.

**Comment by mitar** [comment]
Check if it works. Computer seems that it was not on at the moment.
