### ISSUE TITLE
Can we make a forwarding adress?

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#52]
may we please forward:

maintenance.cloyne.org

to:

https://docs.google.com/a/bsc.coop/forms/d/1taewnS_5NPxYXB9amWRhTp0njiS_443DVpPIVTsAbTI/viewform

to make maintenance request easier to find.

**Comment by mitar** [comment]
Done: https://github.com/cloyne/docker-powerdns-master/commit/7dd2189ee34d89d1a5f4e71174b16aa8b30ee888 https://github.com/cloyne/docker-web/commit/0b8db1afd7bc4d448bf554eae879bfd14c3e15a3
