### ISSUE TITLE
Create a new sheet with instructions for printing

### ISSUE THREAD

**Issue by mitar** [cloyne/network#53]
It seems old one got destroyed and is not there anymore.

**Comment by kelly011235** [comment]
Yeah let's do it

**Comment by mitar** [comment]
Working on instructions [here](https://docs.google.com/document/d/10ZojtIIfZ4qPgmTEA4SqxwkNeaQ68HiVrbbMHQKPUUs/edit?usp=sharing).

**Comment by kelly011235** [comment]
ahhh yes. this document. lezz do it.

**Comment by kelly011235** [comment]
looks a bit better. scroll all the way down

**Comment by kelly011235** [comment]
did i miss anything?

**Comment by mitar** [comment]
Perfect! Print and put it around! :-) Thanks!

**Comment by kelly011235** [comment]
yo mi-

that link to the printing website still isn't working for me:
Your connection is not private

Attackers might be trying to steal your information from *printer1.cloyne.net
<http://printer1.cloyne.net>* (for example, passwords, messages, or credit
cards).

NET::ERR_CERT_AUTHORITY_INVALID

**Comment by mitar** [comment]
Yea, printer is using self-signed certificate. That is how it is. Not a good practice but we cannot do much about that. We can remove the link, if you think it will bring more issues than usefulness.

**Comment by kelly011235** [comment]
hmm i'm not sure if most of the house will be able to navigate it cleanly,
so i would say ditch it.

-kel

ps :D

**Comment by mitar** [comment]
OK. :-)

**Comment by kelly011235** [comment]
I'll print when I get home

On Nov 24, 2015, at 2:14 PM, Mitar <notifications@github.com> wrote:

OK. :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/cloyne/network/issues/53#issuecomment-159423202>.

**Comment by kelly011235** [comment]
close #53
