### ISSUE TITLE
Two static IPs

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#57]
Hey Mitar, 
Can I get two static ips? A WiFi led controller I have doesn't work if it's not on the same 255.255.255.0 network as the phone.

Mac addresses:
Phone c0:ee:fb:5a:4c:d6
Led controller: ac:cf:23:43:a2:74

**Comment by mitar** [comment]
Please connect both devices to the network.

**Comment by jmrtns** [comment]
They should both be connected to wifi no?

**Comment by mitar** [comment]
I have not seen the led controller 5 hours ago. (At least not with the MAC address.)

**Comment by jmrtns** [comment]
My bad, it should be connected now.

**Comment by mitar** [comment]
I still do not see the LED light.

**Comment by jmrtns** [comment]
The LED strip has a current IP of:
10.20.34.71
and a MAC of:
AC:CF:23:43:A2:74

**Comment by mitar** [comment]
I do not see it at all among leases. It is possible that it take the IP, but then releases it?

**Comment by mitar** [comment]
Can you restart the strip like now?

**Comment by jmrtns** [comment]
I just reset it and I'm actively using it so it should be on the network.

**Comment by jmrtns** [comment]
If you tell me the IP to use for it I can try to set it so you don't waste
time.

**Comment by mitar** [comment]
Does it use a static IP or a DHCP? Please configure it to use DHCP.

**Comment by jmrtns** [comment]
It uses dhcp

**Comment by mitar** [comment]
I do not see it at all. I think we should meet it look into this together.

**Comment by jmrtns** [comment]
I got rid of the controller in favor of a raspberry pi
