### ISSUE TITLE
br-lan: received packet on eth0 with own address as source address

### ISSUE THREAD

**Issue by mitar** [cloyne/network#58]
I see in `dmesg` output that all our APs have now such errors:

```
br-lan: received packet on eth0 with own address as source address
```

Is there some network loop happening?

**Comment by jmrtns** [comment]
When did start?

**Comment by mitar** [comment]
I do not know. I just noticed it. We maybe did something in the network closet?

**Comment by jmrtns** [comment]
We can check it out when we put up our side of the Cory link. Cloyne's
Cisco switches should be smart enough not recognize a loop correct, can you
check anything from the Cisco smart switch software?

**Comment by mitar** [comment]
For the record, we do not have Cisco switches. :-)

But you did give me an idea that this might be because of the link towards Euclid?

**Comment by mitar** [comment]
Let's close that and see if this happens once we move to a newer nodewatcher firmware.
