### ISSUE TITLE
Let's upgrade :)

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#64]
http://www.bhphotovideo.com/c/product/1184037-REG/ubiquiti_networks_uap_ac_pro_5_unifi_ap_ac.html

I remember you mentioning something about AC not being good in crowded locations because of the beam-forming. but I can't seem to find anything that supports this. It seems that AC will work as well as it can and then start also using N and because of this actually works better than N. These are $120 each and seem to be much better than the ones we currently have that we could likely give to other houses. It seems that at-least the family room AP gets consistently overloaded around 23:00

We could also replace the tp-links with our older UniFis and donate the rest of our older UniFis to the other houses

**Comment by jmrtns** [comment]
Also, if we do this BSC wide we could probably get very good deals. It seems the houses all had the same CISCOs at one point implying that BSC probably did this before

**Comment by mitar** [comment]
cc @CdavM

At the network managers meeting today we talked about these new APs. The idea is that we test them at some smaller house and see how they work.

I do not think it is worth upgrading at this point for Cloyne though. The speeds are mostly because of additional wider channels and a bit better coding. Nothing which I think would really help. We could maybe instead install one extra AP on a different channel in LibEd or somewhere (maybe just 5 GHz).

So I do not think it is worth investment while other houses are not even on dual-band APs. Sorry. We have it pretty good in comparison with other houses.

Also, I prefer having equipment with Atheros chipset.

**Comment by jmrtns** [comment]
I thought it did have a qualcom atheros chip https://wiki.openwrt.org/toh/ubiquiti/unifiac

**Comment by mitar** [comment]
Oho, they do have Atheros chipset (and are supported by OpenWrt): https://wiki.openwrt.org/toh/ubiquiti/unifiac

@CdavM, I think this should be preferred over current proposed UniFi AP AC. So those rectangular are not good (there are old generation, not supporting OpenWrt, see here: https://www.ubnt.com/unifi/unifi-ap/), but the new ones looks OK, (see here: https://www.ubnt.com/unifi/unifi-ac/). So probably Unifi AC Lite AP could be good enough for us. But Unifi AC Lite AP or UniFi AC Pro AP.

There is also: https://www.ubnt.com/unifi/unifi-ap-ac-edu/ which has speakers. :-)

**Comment by jmrtns** [comment]
I learned my lesson about checking the openwrt page first already =) You can also upgrade the pros to the edus if you buy the speakers and the pros fit in our current UniFi AP mounts so no need for extra installation labor =) AP-AC-PRO are also cheaper than AP-AC, even though they are better, because capitalism

**Comment by mitar** [comment]
Yes. So I agree that it is good for BSC to start buying AP-AC-PROs I do not think the advantage is worth us upgrading our equipment just yet.

**Comment by jmrtns** [comment]
I know it seems biased since my room is next to it but I really think the nice room could benefit from an ap, the internet is okay on the inner part but the outermost part is spotty. The nice room, especially the outer part, is used very often as a study space

**Comment by jmrtns** [comment]
It would be great if I could be informed on the next ap-ac-pro purchase. I was planing on getting a five pack but it would probably be cheaper for BSC and me if we found a bigger pack

**Comment by mitar** [comment]
Sometimes it is good to not have Internet so it helps you focus on studying.

**Comment by mitar** [comment]
> It would be great if I could be informed on the next ap-ac-pro purchase. I was planing on getting a five pack but it would probably be cheaper for BSC and me if we found a bigger pack

For which purpose? Your personal ones? This could be tricky to pull off tax-wise. They cannot just buy stuff and give it to you?

**Comment by jmrtns** [comment]
Yeah for a project back home. No, I would pay for them, we would just be buying them together. so lets say for example BSC needs 5 and I need 5. if a 5 pack is $120 per unit but a 10 pack is $100 per unit then I would give BSC $500 and then BSC would buy a 10 pack saving both parties $100

**Comment by jmrtns** [comment]
Or it could be the other way around if it would make taxes easier

**Comment by mitar** [comment]
> if a 5 pack is $120 per unit but a 10 pack is $100 per unit then I would give BSC $500 and then BSC would buy a 10 pack saving both parties $100

Yes, this would be accounting hell. :-)

**Comment by jmrtns** [comment]
:-1:

**Comment by mitar** [comment]
But talk to them. :-)

**Comment by jmrtns** [comment]
Who do I talk to, David?

**Comment by jmrtns** [comment]
Should we close this since we don't really have much reason to upgrade and it is more something for BSC to consider for other houses? The only thing I see as still potentially live here is adding another 5ghz ap near the family room since it gives WiFi to Nice room, family room, and library, all heavily used study spaces and the ap currently there seems to get overloaded at times

**Comment by CdavM** [comment]
Hi everyone,

I'll keep you posted on our unifi purchases. I was also looking at http://www.open-mesh.com/, their MR1750 seems comparable to ac-pro units. I'll do more research and maybe test them on a small house.

**Comment by jmrtns** [comment]
They seem to have nothing to do with the open source or open hardware community, I cant figure out what is "open" about them. It also seems that you can't flash them with openwrt. Cloudtrax also makes me a little uneasy

**Comment by mitar** [comment]
I know people working on open-mesh. And to my knowledge it is pretty open. They run OpenWrt themselves.

https://help.cloudtrax.com/hc/en-us/articles/202487954-Open-Mesh-and-OpenWRT

**Comment by jmrtns** [comment]
Oh cool! I still couln't find anything on their website speaking to how they are open though but maybe I just didn't understand?
UAP-AC* might have a broadcom chipset :( [https://wikidevi.com/wiki/Ubiquiti_Networks_UniFi_AP_AC_%28UAP-AC%29](url) only the UAP-AC-Lite has a higher chance of having an Atheros based on this [https://wiki.openwrt.org/toh/ubiquiti/unifiac](url) I'm not sure either way

**Comment by mitar** [comment]
No, the link you send is for UAP-AC, this is old (see date). We should look at UAP-AC-PRO.

**Comment by jmrtns** [comment]
I can't seem to find any hard evidence either way, only form posts which mostly say Atheros. Is it strange that the data-sheet doesn't seem to include the information?

**Comment by mitar** [comment]
You can see in [their FCC application files](https://fcc.io/SWX/-UAPACPRO) that chips have [Qualcomm/Atheros logo](https://apps.fcc.gov/eas/GetApplicationAttachment.html?id=2743796).

**Comment by jmrtns** [comment]
That's an interesting way of finding that information out. Thank you so much!

**Comment by mitar** [comment]
I think we will keep current ones for some time. With separation to Cloyne and CloyneSlow SSIDs things are pretty fast.
