### ISSUE TITLE
Try to force clients to use 5 GHz instead of 2.4 GHz

### ISSUE THREAD

**Issue by mitar** [cloyne/network#67]
There are ways (I do not know them yet) to force clients to use 5 GHZ. We should try to get them to us as much 5 GHz as possible.

**Comment by jmrtns** [comment]
Definitely, I know android tends to prefer 2.4. I see a few networks make
two access points, one for 2.4 and one for 5. I'm curious about the
advantages/disadvantages to this approach

**Comment by mitar** [comment]
This is called "band steering" otherwise. You can see [here under "comming soon"](https://www.ubnt.com/unifi/unifi-ac/).

**Comment by mitar** [comment]
Done by creating two SSIDs, `Cloyne` on 5 GHz and `CloyneSlow` on 2.4 GHz.
