### ISSUE TITLE
People have been complaining about slow file server

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#69]
I have no experience with this myself but people are complaining that the file server speed is 20-30Mb/s. Is that normal or should it be faster?

**Comment by mitar** [comment]
On WiFi or ethernet? WiFi maxes out around 20 Mbit/s.

**Comment by ahdinosaur** [comment]
i echo @mitar, was about to ask that.

speed is a ["performance" feature, not a "must be" feature](http://foldingburritos.com/kano-model/). similar to any open source project, feel free to invite and allow people to fix it themselves if they care so much, complaints to commons are similar to [open source consumerism](https://blog.dinosaur.is/workers-of-open-source-unite/).

or suggest that they check their privilege...

**Comment by jmrtns** [comment]
I'm assuming they are using WiFi since I get about 350Mb/s on Ethernet. I just tested on WiFi and it is about 32mb. I'm curious how things like speedtest.net show speeds of 200Mb/s on WiFi on campus, I'm assuming it uses the router somehow instead of the client? Speedof.me only shows about 35Mb on campus. Thanks Mikey, those are great posts. Thank you so much for still being involved in Cloyne =)

**Comment by ahdinosaur** [comment]
no probs, Cloyne is suck :fire:

**Comment by mitar** [comment]
Maybe we can try with wider channels on 5 GHz.

Also, are you sure that when you are connected to WiFi, you are using 5 GHz?

**Comment by mitar** [comment]
> I'm assuming it uses the router somehow instead of the client?

What exactly does this sentence mean?

**Comment by jmrtns** [comment]
> Maybe we can try with wider channels on 5 GHz.
> Also,`are you sure that when you are connected to WiFi, you are using 5 GHz?

I doubt I was connected to 5GHz

> What exactly does this sentence mean?

I don't know how speedtest works I was wondering if it somehow works on the routers Ethernet connection as apposed to the computer which I doubt is even possible. Speed test is apparently very inaccurate http://testmy.net/ipb/topic/28902-why-do-my-results-differ-from-speedtestnet-ookla-speed-tests/.

**Comment by mitar** [comment]
Try to force your computer to connect on 5 GHz and test.

**Comment by mitar** [comment]
> I don't know how speedtest works

Just downloads and uploads from your computer.

>  if it somehow works on the routers Ethernet connection as apposed to the computer which I doubt is even possible.

Why would it do that? That would be an useless speed test. You want to know what is your speed for normal use, so a speed test should try to match that as close as possible. It is not the idea of the speed test to give you as high number as possible. But as realistic one as possible.

You should be using https://www.dslreports.com/speedtest for speeds tests anyway.

**Comment by mitar** [comment]
Over Ethernet I can get 450 Mbit/s to iperf on server2 (#90). I tested if from various places around Cloyne.

WiFi is also upgraded to 40 MHz, so I think this is good enough for now.

**Comment by jmrtns** [comment]
This is re appearing as an issue, iperf is high but actual file downloads, even over ethernet, are pretty slow.
From what I hear it's actually been getting worse.

This may be a RAM issue, Server 3 is currently running at both maximum RAM (8GB) and SWAP(4GB). If whoever installed the OS had used LVM this wouldn't be an issue as we could just resize the LVM SWAP partition =p. We currently have a 120GB SSD in Server 3 with approximate disk usage as follows:
7GB: OS
102GB: Unused
4GB: SWAP

I'm considering taring the root partition, converting the SSD to LVM, and giving the server about 60GB SWAP.

The motherboard is also running at maximum supported ram (8GB DDR2 =p). CPU utilization is at about 0.03% ...

**Comment by mitar** [comment]
What? How could more swap help? Swap just slows things down. This is useless for file serer. File server serves files. There is no point in storing the cache of files it is serving into the swap. Even if it is on flash.

Do not complicate with swap. And I do not see that there are any issues with memory:

```
root@server3:~# free -h
             total       used       free     shared    buffers     cached
Mem:          7.8G       7.6G       163M        75M       222M       6.0G
-/+ buffers/cache:       1.4G       6.4G
Swap:         3.8G        56M       3.7G
```

See, there is 6.4G of free RAM. It is normal that OS uses all available RAM for cache/buffers.

So no, RAM is not an issue here.

I think you should investigate more why it is slow. Start downloading something and then observe. Is it CPU? Is it IO? Network? Drives? Memory?

**Comment by jmrtns** [comment]
Why not use the unused disk space? Yes it's normal for linux to use up all available ram for cach/buffer but not so normal for it to also use up swap. But then again the only file servers I'm used to have commonly accessed files in which case more RAM and SWAP are beneficial. I take it that is not so much the case here since people don't tend to access one file, they access multiple different ones? In this case the limiting factor is definately IO:

On a newly downloaded file:
CPU = 30% idle
IO = 30MB
Network = 240Mb

On a cached file:
CPU = 45% idle
IO = 0MB
Network = 800Mb

But in this case, 240Mb on a brand new file download is still much faster than people should be complaining about, I'll ask the members for more information to see if it is their client or perhaps if it is a switch/cable since I ran these tests from within the network closet. 

It would still be nice to have the SSD on LVM and I don't see an issue with more file caching since the SSD has so much unused space.

**Comment by mitar** [comment]
> Yes it's normal for linux to use up all available ram for cach/buffer but not so normal for it to also use up swap.

I do not see swap as being used?

> Why not use the unused disk space?

Because swap does not really improve things.

>  I'll ask the members for more information to see if it is their client

I think it is simple WiFi limit.

> It would still be nice to have the SSD on LVM and I don't see an issue with more file caching since the SSD has so much unused space.

That SSD is cheap. I would like to write to it as little as possible because it is not in RAID. It is good that we are not using it a lot because it might fail under you.

**Comment by jmrtns** [comment]
It may also be peak usage from multiple people accessing a files. I'll ask people to report when it is actually slow, do we have any logging on server3 that I could look back to about network / CPU usage? At that point it also introduces random read/write which will slow down IO a bit but probably not much due to our RAID configuration.

**Comment by mitar** [comment]
So idea was to install nodewatcher on server3. Then we can do logging of server itself through it. ;-)

But the issue is that nodwatcher also consumes resources so if the server is limited in resources we might not want to do that.

In general all our servers are slow in CPU. I had to remove PeerMind from them because they were simply too slow for MongoDB.

**Comment by mitar** [comment]
Also, as a network manager you should probably not try to solve all problems but prioritize them. You have only 5 hours a week. You do not have to solve all issues. Working but slow file server is better than none at all.

**Comment by mitar** [comment]
(BTW, you should also replace patch cables in network closet with gigabit ones, this might also improve things.)

**Comment by jmrtns** [comment]
It's not really a very cheap SSD, The installed Samsung EVO 840 PRO is a relatively nice SSD.

wow... I misread top... SWAP is not used at all... my bad =(

**Comment by jmrtns** [comment]
in regards to our server not being able to host PeerMind #98 =)

**Comment by jmrtns** [comment]
I'll close this for now and it can be revisited after nodewatcher is installed.
