### ISSUE TITLE
Redo all patch cables in the network closet(s)

### ISSUE THREAD

**Issue by mitar** [cloyne/network#87]
We have replacement cables, we should redo all patch cables.

We have ethernet cables/patch cables:
* 2ft Black – for network closets around Cloyne, to connect switches to rooms, top row
* 2ft Grey – for network closets around Cloyne, to connect switches to rooms, bottom row
* 5ft Grey – to connect servers
* 5ft Yellow – for uplink in the server room
* 2ft Yellow – for uplink for switches in network closets around Cloyne
* 2ft Green – to connect APs
* 2ft Blue – for mesh antennas

**Comment by eranda2595** [comment]
I'm doing this. @tuesday, nov. 13th morning.

**Comment by eranda2595** [comment]
central and east wing [before]

![14303829_886126851532242_1753933999_o](https://cloud.githubusercontent.com/assets/13376501/18500398/f3817f4e-79fb-11e6-90c3-b3046ddef8c4.jpg)
![14303934_886126774865583_588666625_o](https://cloud.githubusercontent.com/assets/13376501/18500400/f781fae2-79fb-11e6-848e-f22ea4e89c80.jpg)
![14315899_886126848198909_1512925235_o](https://cloud.githubusercontent.com/assets/13376501/18500405/fceb215c-79fb-11e6-9fe8-238de49944b5.jpg)
![14339364_886126841532243_1599139860_o](https://cloud.githubusercontent.com/assets/13376501/18500407/feb31ca6-79fb-11e6-905d-a8093d9d99da.jpg)
![14340068_886126788198915_1973665581_o](https://cloud.githubusercontent.com/assets/13376501/18500408/01ecdcc2-79fc-11e6-9636-1491cde77b60.jpg)
![14360466_886126794865581_1132807515_o](https://cloud.githubusercontent.com/assets/13376501/18500409/04743576-79fc-11e6-8ab2-d3371cabfc83.jpg)
![14360528_886126838198910_470833078_o](https://cloud.githubusercontent.com/assets/13376501/18500412/07474ef0-79fc-11e6-9ad6-caddfcb05acc.jpg)

**Comment by eranda2595** [comment]
central and east wing [after] new system~ 😄 

![14303816_886126804865580_1368360324_o](https://cloud.githubusercontent.com/assets/13376501/18500425/2cbac3c4-79fc-11e6-8099-efab20086e9f.jpg)
![14315530_886126818198912_1728447968_o](https://cloud.githubusercontent.com/assets/13376501/18500431/336215ec-79fc-11e6-8651-c7ed57d78645.jpg)
![14329398_886126771532250_1993067484_o](https://cloud.githubusercontent.com/assets/13376501/18500435/35f25970-79fc-11e6-909a-d50780c4af55.jpg)
![14339923_886126778198916_1358407331_o](https://cloud.githubusercontent.com/assets/13376501/18500436/382b7168-79fc-11e6-805e-1847e2768e36.jpg)
![14359723_886126814865579_121272252_o](https://cloud.githubusercontent.com/assets/13376501/18500438/3aabdcca-79fc-11e6-95a5-b8ee732784ea.jpg)
![14374532_886126821532245_596511212_o](https://cloud.githubusercontent.com/assets/13376501/18500441/402947f0-79fc-11e6-8309-8fd09d0373bc.jpg)
![14374661_886126834865577_1198464065_o](https://cloud.githubusercontent.com/assets/13376501/18500443/42ffd048-79fc-11e6-9cc0-2d67034aba85.jpg)
![14374776_886126801532247_1013506861_o](https://cloud.githubusercontent.com/assets/13376501/18500444/46da0120-79fc-11e6-978a-8f3137f64db3.jpg)

**Comment by mitar** [comment]
Hm, which photo is which network closet? Can you write above each photo?

**Comment by eranda2595** [comment]
[Central] before-after

2nd floor ~
before
![14303829_886126851532242_1753933999_o](https://cloud.githubusercontent.com/assets/13376501/18500533/1f8a19a6-79fd-11e6-82c9-de6c46358be1.jpg)
![14339364_886126841532243_1599139860_o](https://cloud.githubusercontent.com/assets/13376501/18500538/2396d85e-79fd-11e6-9dd8-f58d5359e725.jpg)

after
![14315530_886126818198912_1728447968_o](https://cloud.githubusercontent.com/assets/13376501/18500554/41e3b386-79fd-11e6-9766-3527cecdbd05.jpg)
![14303947_886126831532244_754917337_o](https://cloud.githubusercontent.com/assets/13376501/18500557/46cd1658-79fd-11e6-8d9d-149b818c0a8e.jpg)
![14315530_886126818198912_1728447968_o](https://cloud.githubusercontent.com/assets/13376501/18500582/8bc47526-79fd-11e6-8426-7480df3f2914.jpg)



3rd floor ~ with new system

![14374776_886126801532247_1013506861_o](https://cloud.githubusercontent.com/assets/13376501/18500577/7b03b774-79fd-11e6-990b-774ddc56ea6f.jpg)
![14374661_886126834865577_1198464065_o](https://cloud.githubusercontent.com/assets/13376501/18500579/7d2026dc-79fd-11e6-9182-0d9d5e79f459.jpg)
![14359723_886126814865579_121272252_o](https://cloud.githubusercontent.com/assets/13376501/18500581/822d904c-79fd-11e6-91d4-c7e9abb449a8.jpg)

**Comment by eranda2595** [comment]
# **East wing [before-after]**

## _2nd floor [before]
![14360466_886126794865581_1132807515_o](https://cloud.githubusercontent.com/assets/13376501/18500614/f6d09f2a-79fd-11e6-8560-cb08b6f627d6.jpg)
_

![14340068_886126788198915_1973665581_o](https://cloud.githubusercontent.com/assets/13376501/18500601/ddb621ea-79fd-11e6-8cbb-67936ca375f1.jpg)

**Comment by mitar** [comment]
(You could just edit the comments.)

**Comment by eranda2595** [comment]
@mitar yah i know but I did them separately for each wing :)

**Comment by eranda2595** [comment]
but like isn't there only one network closet per floor? [floor no, wing name]

**Comment by mitar** [comment]
I updated labels so that they are consistent. :-)

**Comment by eranda2595** [comment]
looks better, thank you!! :)

**Comment by ahdinosaur** [comment]
oooh, so great! :sparkles:

**Comment by mitar** [comment]
@eranda2595: Please update the issue with latest information on the progress.

Also do not throw simply everything into the electronic waste. Not everything is electronic waste. Some things are simply soft plastic (like bags). Please clean that up.

Also, in general, make space around switches tidy. Do not leave wires hanging around so that others might hit them when they are using closets.

**Comment by eranda2595** [comment]
@mitar will do. here's the updated info for now.

West Wing [2nd floor]
before

![14375294_889756844502576_81726947_o](https://cloud.githubusercontent.com/assets/13376501/18655117/160537d8-7e9b-11e6-8ab9-e0a086a8e2d1.jpg)
![14407973_889756894502571_77710121_o](https://cloud.githubusercontent.com/assets/13376501/18655120/1c8bbf8c-7e9b-11e6-9c48-1af6a9a26947.jpg)
![14375294_889756844502576_81726947_o](https://cloud.githubusercontent.com/assets/13376501/18655132/3265345a-7e9b-11e6-8467-18b9c20c6d9d.jpg)

after
![14393211_889756891169238_894260219_o](https://cloud.githubusercontent.com/assets/13376501/18655144/42452d08-7e9b-11e6-911a-050bd883aa94.jpg)

**Comment by eranda2595** [comment]
mailroom [first floor]

![14408107_889756881169239_1669728217_o](https://cloud.githubusercontent.com/assets/13376501/18655151/5908e35e-7e9b-11e6-92d3-27a6cafa8ecd.jpg)

after 
![14423715_889756871169240_1493890897_o](https://cloud.githubusercontent.com/assets/13376501/18655165/6696aaba-7e9b-11e6-9a1b-c7e63fa3bcde.jpg)

**Comment by mitar** [comment]
You didn't do the third floor, west wing.

**Comment by eranda2595** [comment]
##West Wing 

[3rd floor]
#before
![14625763_902403499904577_1318780331_o](https://cloud.githubusercontent.com/assets/13376501/19227908/7890fa5c-8e74-11e6-9df7-52f1506c0aa2.jpg)

#after
![14625621_902403486571245_1265499890_o](https://cloud.githubusercontent.com/assets/13376501/19227910/80f35474-8e74-11e6-9c7d-e380bfb64ea2.jpg)

[2nd floor]
![14614336_902403503237910_1619918964_o](https://cloud.githubusercontent.com/assets/13376501/19227957/0a16d442-8e75-11e6-9ed7-0966761b7fea.jpg)

**Comment by mitar** [comment]
For second floor please update the comment above, where is already one photo.

Also, format text around images in the same way as other comments are. You can click on edit button to see Markdown syntax used.

Moreover, why 4 yellow cables on the third floor?

**Comment by mitar** [comment]
And on the second floor you mixed one black cable.

**Comment by mitar** [comment]
Also, upload new photos for east wing.

**Comment by eranda2595** [comment]
@mitar 

1. updated. 
2. thanks.  updated the syntax and should be fixed. 
3. needed to check with you about that because I assumed the yellow for uplink cable. 

--
1. we ran out of grey cables, that's why I had to use that. 
--
1. uploaded.

**Comment by mitar** [comment]
We care only about the latest state of our improvements. So we want old photos, and latest state of improvements. (In west wing 2nd floor you have old improved and new improved photo.)

> we ran out of grey cables, that's why I had to use that. 

You should not reuse the color which is meaningful in the same context. Which of those cables are not an uplink? Reuse old cables and then we can buy one more set of cables.

Why you didn't report here that we ran out of cables? We could already order new ones and have them delivered today. It is at least 2 days ago since you noticed that we ran out of cables.

In east wing you have old photos for latest state. We moved all cables to come from the right. Please update photos with latest state.

So west wing third floor cables are mixed. And second floor west wing one cable is mixed. Moreover, you do not start from right with rooms, as we discussed. You should start from right with rooms, and then left top set of ports is used for special ports.

**Comment by mitar** [comment]
OK, I went through all cabinets and fixed the cables and labeled them. I also replaced old 100 Mbit/s switches with new small Gigabit. I updated photos above with the latest state of all cabinets.

This is now done.

@eranda2595, thanks for all the help!
