### ISSUE TITLE
Blacklisted IP

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#96]
The ip we use for member's internet is blacklisted from a few sites (dreamHost atleast). I've contacted HE but I now need to contact dreamHost and see where they got the blacklist from. from there it us just a matter of filling out a form. This however will probably be a recurring issue as we have more than 200 clients and high turnover so it's very likely that someone in our network has a virus that gets the IP blacklisted. Not sure if this is an issue to keep addressing or not.

**Comment by jmrtns** [comment]
"Hello,

I usually find the mxtoolbox blacklist tool very useful when trying to see where an IP address is blacklisted:

http://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a64.62.133.42&run=toolpage#

Although this does not account for every single public blacklist, it does cover a wide range of them.

From this, I see you are blacklisted on the BARRACUDA blacklist.

If you would like to get removed from this list, please fill out the form at:

http://barracudacentral.org/rbl/removal-request
"

- our ISP's support.

I don't feel very inclined to fill out the form because we will probably get blacklisted again with all our clients...

**Comment by mitar** [comment]
I think this is not the case. What often those blacklists are for sending spam. But in this case it is probably not about spam but that our traffic is not coming from residential ISP.

Wikipedia has the same blacklist. You cannot edit Wikipedia through our connection, but you have to be registered. This is a downside of this proxy approach, but filling out forms did help in the past. So I would urge you to go and fill them.

Writing to HE is pointless, they have nothing with this.

You should just write to all people who are blocking and ask them to unblock. And then if they say that they are using some blacklist you write to that blacklist. Have you contacted dreamHost?

**Comment by jmrtns** [comment]
I couldn't find any contact information about contacting dreamHost. They seem to only have contact information for customers. So it is worth it to fill out the baracuda form then?

**Comment by mitar** [comment]
You just write to `abuse@dreamHost.com`.
