### ISSUE TITLE
Install/configure servers for salt

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#97]
https://saltstack.com/

**Comment by mitar** [comment]
We use [central git repository](https://github.com/cloyne/servers) and `salt-ssh` so we do not need master/minion approach to Salt. We are simple.

We also moved all our configuration now to [Salt in git](https://github.com/cloyne/servers). We do not yet store any secrets there though, they are mostly configured through binding outside volumes into Docker containers. So not all configuration is really in Salt. Some is in files on servers, mounted in.
